### ISSUE TITLE
Chef build fails

### ISSUE THREAD

**Issue by guewen** [akretion/ak-magento#5]
Here is the log:
```
[2015-02-12T08:20:27+00:00] INFO: Forking chef instance to converge...
[2015-02-12T08:20:27+00:00] INFO: *** Chef 12.0.3 ***
[2015-02-12T08:20:27+00:00] INFO: Chef-client pid: 3412
[2015-02-12T08:20:28+00:00] INFO: Setting the run_list to ["recipe[ak-magento]"] from CLI options
[2015-02-12T08:20:28+00:00] INFO: Run List is [recipe[ak-magento]]
[2015-02-12T08:20:28+00:00] INFO: Run List expands to [ak-magento]
[2015-02-12T08:20:28+00:00] INFO: Starting Chef Run for precise32
[2015-02-12T08:20:28+00:00] INFO: Running start handlers
[2015-02-12T08:20:28+00:00] INFO: Start handlers complete.
[2015-02-12T08:20:28+00:00] ERROR: Running exception handlers
[2015-02-12T08:20:28+00:00] ERROR: Exception handlers complete
[2015-02-12T08:20:28+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2015-02-12T08:20:28+00:00] ERROR: Cookbook loaded at path(s) [/etc/chef-solo/cookbooks/cookbooks/ak-magento] has invalid metadata: The `name' attribute is required in cookbook metadata
[2015-02-12T08:20:28+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

And the content of `/var/chef/cache/chef-stacktrace.out`
```
Generated at 2015-02-12 08:20:28 +0000
Chef::Exceptions::MetadataNotValid: Cookbook loaded at path(s) [/etc/chef-solo/cookbooks/cookbooks/ak-magento] has invalid metadata: The `name' attribute is required in cookbook metadata
/opt/chef/embedded/apps/chef/lib/chef/cookbook/cookbook_version_loader.rb:190:in `raise_metadata_error!'
/opt/chef/embedded/apps/chef/lib/chef/cookbook/cookbook_version_loader.rb:79:in `load'
/opt/chef/embedded/apps/chef/lib/chef/cookbook_loader.rb:83:in `block in load_cookbook'
/opt/chef/embedded/apps/chef/lib/chef/cookbook_loader.rb:82:in `each'
/opt/chef/embedded/apps/chef/lib/chef/cookbook_loader.rb:82:in `load_cookbook'
/opt/chef/embedded/apps/chef/lib/chef/cookbook_loader.rb:72:in `block in load_cookbooks'
/opt/chef/embedded/apps/chef/lib/chef/cookbook_loader.rb:71:in `each'
/opt/chef/embedded/apps/chef/lib/chef/cookbook_loader.rb:71:in `load_cookbooks'
/opt/chef/embedded/apps/chef/lib/chef/policy_builder/expand_node_object.rb:61:in `setup_run_context'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:235:in `setup_run_context'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:397:in `run'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:261:in `block in fork_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:249:in `fork'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:249:in `fork_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:215:in `block in run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/local_mode.rb:38:in `with_server_connectivity'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:201:in `run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:245:in `block in interval_run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:234:in `loop'
/opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:234:in `interval_run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:224:in `run_application'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:58:in `run'
/opt/chef/embedded/apps/chef/bin/chef-solo:25:in `<top (required)>'
/usr/bin/chef-solo:40:in `load'
```

**Comment by matthieuchoplin** [comment]
I propose a pull request for fixing this issue here: https://github.com/akretion/ak-magento/pull/6

**Comment by guewen** [comment]
Thanks @matthieuchoplin
